SELECT * FROM customer LIMIT 20

-- # Questions to Annswer for Businesss Purpose 
-- Q1. What is the total revenue generated by male vs. female customer?
SELECT gender , SUM(purchase_amount) as Revenue
FROM customer
GROUP BY gender;

-- Q2. Which customer used a discount but still spent more than average purchase amount?
SELECT customer_id , purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased , ROUND(AVG(review_rating::numeric),2) as Review_Rating
FROM customer
GROUP BY item_purchased
ORDER BY avg(review_rating) desc
LIMIT 5;

-- Q4. Compare average purchase amounts between standard and express shipping.
SELECT shipping_type , ROUND(AVG(purchase_amount),2) as AVG_Purchase_amount
FROM customer
WHERE shipping_type IN ('Standard' , 'Express')
GROUP BY shipping_type;

-- Q5. Do subscribe customers spends more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status , COUNT(subscription_status) as total_count , ROUND(AVG(purchase_amount),2) as AVG_Amount , ROUND(SUM(purchase_amount),2)
FROM customer
GROUP BY subscription_status;

SELECT subscription_status , COUNT(*) as total_count , ROUND(AVG(purchase_amount),2) as avg_spend , SUM(purchase_amount) as total_revenue
FROM customer
GROUP BY subscription_status;

-- Q6. Which 5 products have highest percentage of purchase with discount applied?
SELECT item_purchased , COUNT(*) as total_purchases,
SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) as discounted_purchases,
ROUND((SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100 /COUNT(*)),2) as discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

SELECT item_purchased , COUNT(*) as total_count,
SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) as discounted_purchases,
ROUND((SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)* 100 / COUNT(*)),2) as discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q7. Segment customers into new , returning , and loyal based on their total number of previous purchases , and show the count of each segment.
WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
	FROM customer
)
SELECT customer_segment , COUNT(*) as "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased product within each category?
SELECT category , item_purchased , purchase_count
FROM (
	SELECT category , item_purchased , COUNT(*) as purchase_count,
	RANK() OVER(PARTITION BY category ORDER BY COUNT(*) DESC) as rnk
	FROM customer
	GROUP BY category , item_purchased
)ranked
WHERE rnk <= 3
ORDER BY category , purchase_count DESC;

-- Using Rank()
SELECT category , item_purchased , total_count
FROM(
	SELECT category , item_purchased , COUNT(*) as total_count,
	RANK() OVER(PARTITION BY category ORDER BY COUNT(*) DESC) as rnk
	FROM customer
	GROUP BY category , item_purchased
) ranked
WHERE rnk <=3
ORDER BY category , total_count DESC;

-- Using Row_Number()
WITH product_count AS(
SELECT category , item_purchased , COUNT(*) as total_count,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(*) DESC) as product_rank
FROM customer 
GROUP BY category , item_purchased
)
SELECT product_rank , category , item_purchased , total_count
FROM product_count
WHERE product_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe? (Customers > 5 are subscribers?)
SELECT subscription_status , COUNT(*) as repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. Whats is the revenue contribution of each age group?
SELECT age_group , SUM(purchase_amount) as Revenue
FROM customer
GROUP BY age_group
ORDER BY revenue DESC;

SELECT age_group , SUM(purchase_amount) as revenue
FROM customer
GROUP BY age_group
ORDER BY revenue DESC;